apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkid
  labels:
    app.kubernetes.io/name: arkid
    helm.sh/chart: arkid-1.4.0
    app.kubernetes.io/instance: arkid
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: arkid
      app.kubernetes.io/instance: arkid
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arkid
        app.kubernetes.io/instance: arkid
    spec:
      initContainers:
      - image: busybox
        command:
        - sh
        - -c
        - echo 65535 > /proc/sys/net/core/somaxconn
        imagePullPolicy: Always
        name: setsysctl
        securityContext:
          privileged: true
      containers:
        - name: "arkid-web-server"
          image: skaffold-arkid-be
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping/
              port: http
          readinessProbe:
            httpGet:
              path: /ping/
              port: http
          volumeMounts:
            - name: "settings-local"
              mountPath: "/var/oneid/settings_local.py"
              subPath: "settings_local.py"
            - name: arkid-data
              mountPath: /var/oneid/upload
              subPath: be/upload
            # @TODO: mount plugins
            # - name: arkid-data
            #   mountPath: /var/oneid/plugins
            #   subPath: be/plugins

        - name: "arkid-web-server-broker"
          image: "longguikeji/arkid-broker:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args: ["broker", "-t", "http://localhost", "-p", "8080"]

        - name: "arkid-redis"
          image: "redis:5.0.3"
          imagePullPolicy: IfNotPresent

        - name: "arkid-mysql-database"
          image: "mysql:5.7"
          imagePullPolicy: IfNotPresent
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          volumeMounts:
            - name: arkid-data
              mountPath: /var/lib/mysql
              subPath: mysql/data
            - name: arkid-data
              mountPath: /etc/mysql/conf.d
              subPath: mysql/config

        - name: "arkid-ldap"
          image: "longguikeji/ark-sql-ldap:1.2.0"
          imagePullPolicy: IfNotPresent
          env:
          - name: SQL_HOST
            value: "127.0.0.1"
          - name: SQL_PORT
            value: "3306"
          - name: SQL_USER
            value: "root"
          - name: SQL_PWD
            value: "root"
          - name: LDAP_PASSWORD
            value: "admin"
          - name: SQL_DB
            value: "arkid"
          - name: BACKEND
            value: "sql"

      volumes:
        - name: settings-local
          configMap:
            name: arkid
        - name: arkid-data
          persistentVolumeClaim:
            claimName: arkid