# Generated by Django 3.2.6 on 2021-08-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0018_alter_tenantdevice_device_type'),
        ('tenant', '0018_tenantuserprofileconfig'),
    ]

    operations = [
    ]
