# Generated by Django 3.2.6 on 2021-08-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0019_merge_20210816_1221'),
        ('tenant', '0019_tenantpasswordconfig'),
    ]

    operations = [
    ]
