# Generated by Django 3.2.6 on 2021-08-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0019_delete_tenantdevice'),
        ('tenant', '0020_merge_20210817_0106'),
    ]

    operations = [
    ]
