# Generated by Django 3.2.6 on 2021-08-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0021_tenantauthfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantauthfactor',
            name='description',
        ),
        migrations.AddField(
            model_name='tenantauthfactor',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
            preserve_default=False,
        ),
    ]
