# Generated by Django 3.2.6 on 2021-08-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0021_merge_20210817_0906'),
        ('tenant', '0024_tenantauthrule'),
    ]

    operations = [
    ]
