# Generated by Django 3.2.6 on 2021-08-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0022_tenantlogconfig'),
        ('tenant', '0025_merge_0021_merge_20210817_0906_0024_tenantauthrule'),
    ]

    operations = [
    ]
