# Generated by Django 3.2.6 on 2021-08-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0026_merge_20210817_1234'),
        ('tenant', '0026_tenantlogconfig'),
    ]

    operations = [
    ]
