# Generated by Django 3.2.6 on 2021-08-18 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0027_merge_0026_merge_20210817_1234_0026_tenantlogconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantagentrule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantauthfactor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantauthrule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantcontactsconfig',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantcontactsuserfieldconfig',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantdesktopconfig',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantlogconfig',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantpasswordcomplexity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantpasswordconfig',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantprivacynotice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='tenantuserprofileconfig',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
    ]
