# Generated by Django 3.2.6 on 2021-08-18 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_merge_20210325_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
    ]
