# Generated by Django 3.2.6 on 2021-08-18 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0028_auto_20210818_0158'),
        ('webhook', '0005_auto_20210722_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='密钥'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
    ]
