# Generated by Django 3.2.6 on 2021-08-18 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0028_auto_20210818_0158'),
        ('app', '0006_app_auth_tmpl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='auth_tmpl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='认证模板'),
        ),
        migrations.AlterField(
            model_name='app',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='额外数据'),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='app',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='app',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.CharField(max_length=128, verbose_name='应用类型'),
        ),
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.CharField(blank=True, max_length=1024, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='app',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
    ]
