# Generated by Django 3.2.6 on 2021-08-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210817_1140'),
        ('inventory', '0015_auto_20210817_1348'),
    ]

    operations = [
    ]
