version: '3.5'

services:
  portal:
    image: nginx:alpine
    container_name: arkid-portal
    restart: always
    networks:
      - arkid
    ports:
      - 8989:80
    depends_on:
      - be
      - fe
    volumes:
      - ./portal.conf:/etc/nginx/conf.d/default.conf

## arkid-dev
  be:
    image: arkid-dev:latest
    container_name: arkid-be
    sysctls:
      - net.core.somaxconn=65535
    restart: always
    working_dir: /root/workspace/arkid
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python manage.py migrate && tail -f /dev/null"
    networks:
      - arkid
    depends_on:
      - db
    volumes:
      - ./be/upload:/root/workspace/arkid/upload
      - ./be/plugins:/root/workspace/arkid/plugins
      - ../../:/root/workspace/arkid
      - ./be/settings.py:/root/workspace/arkid/settings_local.py
      - ../../uwsgi.ini:/etc/uwsgi/uwsgi.ini

  # 如果不开发后端，请用这个
  # be:
  #   image: longguikeji/arkid:1.4.4
  #   container_name: arkid-be
  #   sysctls:
  #     - net.core.somaxconn=65535
  #   restart: always
  #   networks:
  #     - arkid
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./be/settings.py:/var/oneid/settings_local.py
  #     - ./be/upload:/var/oneid/upload
  #     - ./be/plugins:/var/oneid/plugins


  # 如果不开发前端，请用这个
  # fe:
  #   image: longguikeji/arkid-fe:1.4.2
  #   container_name: arkid-fe
  #   restart: always
  #   networks:
  #     - arkid
  fe:
    # image: newbe36524/vscode_typescript_node:0-10
    image: node:8.15
    container_name: arkid-fe
    restart: always
    working_dir: /root/workspace/arkid-fe
    command: sh -c "yarn install --ignore-engines --frozen-lockfile --non-interactive && tail -f /dev/null"
    networks:
      - arkid
    volumes:
      - /Users/notevery/VSCode/arkid-frontend:/root/workspace/arkid-fe

  db:
    image: mysql:5.7
    container_name: arkid-db
    restart: always
    networks:
      - arkid
    environment:
      - MYSQL_DATABASE=arkid
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  ldap:
    image: longguikeji/ark-sql-ldap:1.3.0
    container_name: arkid-ldap
    restart: always
    networks:
      - arkid
    depends_on:
      - be
    ports:
      - 10389:389
    environment:
      - SQL_HOST=arkid-db
      - SQL_PORT=3306
      - SQL_USER=root
      - SQL_PWD=root
      - LDAP_PASSWORD=root
      - SQL_DB=arkid
      - BACKEND=sql
      - SLAPD_NOFILE_SOFT=10000

  redis:
    image: redis:5.0.3
    container_name: arkid-redis
    restart: always
    networks:
      - arkid

networks:
  arkid:
    name: arkid
    driver: bridge
