# Generated by Django 3.2.6 on 2021-08-16 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0016_merge_20210806_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('type', models.CharField(choices=[('dingding', 'Ding Ding'), ('weixin', 'Enterprise WeiChat'), ('scim', 'Scim')], max_length=32, verbose_name='Data Sync Type')),
                ('sync_direction', models.CharField(choices=[('upstream', 'To ArkID'), ('downstream', 'From ArkID')], max_length=32, verbose_name='Sync Direction')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=32)),
                ('mapping', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
